### PR TITLE
Matteo/str

### PR DESCRIPTION
**Pull request by teocomi**

### CODE REVIEW

**Comment by didimitrie** [comment]
@teocomi, does this nugetify the whole thing, or just the class definitions?

**Comment by didimitrie** [comment]
I'm actually signing off, so we'll talk monday 💋

**Comment by teocomi** [comment]
Classes, GSA & Revit. Should they be individual nugets?

**Comment by mishaelnuh** [comment]
May be a good idea to have the structural stuff as a separate nuget. Talk monday 💋

**Comment by teocomi** [comment]
Is Elements actually going to be used as a nuget? If only called via reflection, there's no need to reference it...

**Comment by didimitrie** [comment]
the conversion parts are called via reflection; but i can see a use-case on referencing the object model itself (to build on top, around, etc.) in another project.

**Pull request merged**
