### PR TITLE
add typeParameters

### PR DESCRIPTION
**Pull request by htlcnn**
Attemp to solve #26 
@didimitrie @teocomi please discuss.
With my noob C# skill, all I did was copy existing code and modify a little. I don't know how to test.
Thanks.

### CODE REVIEW

**Review by teocomi — COMMENTED** [review]
Thanks for this, I see two possible issues/changes:
- adding the `typeParametes` field this way it'll be visible in the schema builder in grasshopper, is it acceptable @didimitrie ? Should we nest it inside `parameters` instead?
- I'm not sure we need the `SetElementTypeParams` method. Being those **type parameters** they'll already exist in the Revit types upon receiving the data, and I'm not sure we want to override their values as it could be easily misused... What do you think @htlcnn ?

**Comment by htlcnn** [comment]
@teocomi 
At the beginning, I only thought of how to push type parameters from Revit to Speckle so that I would manipulate them. Until you talked about converting from Speckle to Revit, I got it why you had to separate ConversionRoutine into different classes, so I tried not to miss any step you did to `parameters`.
In case element's type exists before converting from Speckle to Revit Element, I agree that type parameters should not be overridden. I'll remove `SetElementTypeParams` after nesting discussion is finished.

Nesting `typeParameters` inside `parameters` is a little struggle for me because of my C# skill. I also read your code that: [BIG CORE PROBLEM: failure to serialise things with nested dictionary](https://github.com/speckleworks/SpeckleElements/blob/master/SpeckleElementsRevit/ConversionsBase.cs#L179), so I didn't try to nest them.

**Comment by teocomi** [comment]
Hi @htlcnn, I've thought about it and it's fine to have `typeParameters` at the top level, if you remove `SetElementTypeParams` I'll merge!

**Comment by htlcnn** [comment]
@teocomi I removed `SetELementTypeParams`.
Thanks!

**Comment by htlcnn** [comment]
@teocomi ping

**Comment by teocomi** [comment]
Sorry for the delay @htlcnn , last week was a bit crazy. Merged in #29, let us know if you need a release!

**Comment by htlcnn** [comment]
@teocomi thanks. I'm just testing so a release is not needed ATM.

**Pull request merged**
